### ISSUE TITLE
invalid regexp on windows

### ISSUE THREAD

**Issue by juliangruber** [docs/data-directory#4]
```
(node:8000) UnhandledPromiseRejectionWarning: SyntaxError: Invalid regular expression: /\/: \ at end of pattern
    at new RegExp (<anonymous>)
    at Object.<anonymous> (C:\Users\Julian\Documents\xxx\node_modules\@github-docs\data-directory\lib\filename-to-key.js:4:23)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\Julian\Documents\xxx\node_modules\@github-docs\data-directory\index.js:7:23)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
```

**Comment by juliangruber** [comment]
this was on an old version of this module
